### PR TITLE
Add followCursor: 'initial' option

### LINKED ISSUE #373: Feature Request: followCursor once
I would like the pop-up to appear near the cursor, but not follow it. In my situation, I have a pop-up associated with a row in a table that is the width of the screen. I'd like the pop-up to be near the mouse, but not jump around once it appears.

Maybe a new option 

followCursor: "initial"

or something like that. Thanks for a great little package!

### PR DESCRIPTION
**Pull request by atomiks**
Resolves #373 

Check it out @dkulp2?

### CODE REVIEW

**Comment by KubaJastrz** [comment]
Please, add that option to types file.

**Comment by dkulp2** [comment]
As long as the listener is sure to be attached with that value to begin with, looks great to me!

**Comment by atomiks** [comment]
> As long as the listener is sure to be attached with that value to begin with, looks great to me!

Yeah it just checks for a truthy value to determine if it should be attached. It think this is the same as the `nearCursor` option that was proposed a few months ago, for some reason I didn't think it would be so simple

**Comment by atomiks** [comment]
This allows you to implement "native" (at least on macOS) tooltip behavior. It will show up at a `bottom-start` placement at the initial cursor position. Cool feature I think 😌

**Comment by clbn** [comment]
@atomiks It seems this also closes #272?

**Comment by atomiks** [comment]
Yeah it seems so, lol

**Comment by clbn** [comment]
@atomiks
By the way, is there a way to combine `followCursor: 'initial'` and `placement: 'bottom'`? I need this feature now but couldn't find the way. So the tooltip would show up at mouse's horizontal position, and using the trigger's `bottom` for vertical coordinate. For "wide table example", this would be quite useful as it would not cover the row itself and look more "orderly".

**Comment by atomiks** [comment]
I think I know what you mean, you don't want it to vertically overlap but still position itself at the curosr on the horizontal axis.

I was working on that for inline elements specifically, but inline positioning might need to be integrated into Popper.js itself 

> Popper.js does not support smart inline element positioning. You can view [one technique here](https://codepen.io/atomiks/pen/GeBoyW?editors=0010)

(there used to be a bug with flipping in some cases, but I can't replicate it anymore)

You can modify it so it uses the event coords for left/right: https://codepen.io/atomiks/pen/GRKGwQa?editors=0110

**Pull request merged**
