### PR TITLE
Update readme with example

### PR DESCRIPTION
**Pull request by adamgen**
Without it, it wasn't clear how to import the css.

### CODE REVIEW

**Comment by KubaJastrz** [comment]
Good idea 👍 

Maybe we could reuse the same text copy and snippet as in [Getting Started](https://atomiks.github.io/tippyjs/getting-started/#1-package-manager) docs?

**Comment by adamgen** [comment]
I'll add tomorrow 👍🏼

**Comment by adamgen** [comment]
@KubaJastrz I used slightly a different snipped, let me know if there's anything else I can help with.

**Comment by atomiks** [comment]
I've added some more info for this myself

**Pull request closed without merging**
