### PR TITLE
Follow cursor fix

### PR DESCRIPTION
**Pull request by atomiks**
ping @TGotwig

Does this fix the issue?

(`npm run build` this branch and grab the dist file)

### CODE REVIEW

**Comment by TGotwig** [comment]
No it's like before.

**Comment by atomiks** [comment]
I noticed the 'files changed' doesn't show the diff... Just to verify, is this piece in the build?

```javascript
// Set initial positioning near cursor (document mousemove may not fire)
if (options.followCursor) {
  this._followCursorListener(event)
}
```

**Comment by TGotwig** [comment]
Where these lines of code should be?
Hmm maybe you can reproduce it by using firefox and increase mouse speed 🤔

**Comment by atomiks** [comment]
inside `_getEventListeners()` method in the Tippy class

**Comment by atomiks** [comment]
You're right! Just used Firefox and moved the cursor really slow on your CodePen, and it happened. Let me see if I can reproduce it with this new version...

**Comment by atomiks** [comment]
I believe the latest commit should fix it. It was updating the popper's position when mounting but it shouldn't if the `followCursor` option is true.

**Comment by TGotwig** [comment]
omg it works! 😱😱
Thanks for the fast fix and make this awesome lib even more awesome 💪👌🎉

**Pull request merged**
