### PR TITLE
fix #221 do not show on disabled elements in FF

### LINKED ISSUE #221: Tippy not registering disabled attribute in Firefox
Tippy will pop up on elements with disabled attribute in Firefox
Other browsers seem to work fine.

see: https://codepen.io/anon/pen/JLzxpE

Tested with firefox ESR 52 and firefox 58
im not even sure whether this is a tippy or a firefox bug...

### PR DESCRIPTION
**Pull request by jburghardt**
fix for FF as described in #221

### CODE REVIEW

**Comment by jburghardt** [comment]
You a right,
that works better

**Comment by atomiks** [comment]
Travis build failed because of `"` instead of `'`

**Comment by jburghardt** [comment]
My bad, hope this will work now

**Comment by atomiks** [comment]
Thank you for the contribution 😊

**Pull request merged**
