### PR TITLE
Add support for array of elements as selector parameter

### PR DESCRIPTION
**Pull request by artyomtrityak**
For apps it can be helpful to pass array of elements instead of doing it one by one.
For example React.js app

```jsx
const titleEls =  Array.prototype.slice.call(
    ReactDOM.findDOMNode(this).querySelectorAll('[title]')
);
tippy(titleEls, {arrow: true});
```

P.S. Is there any instruction how to run tests? 

```bash
npm run tests
> rollup -c scripts/rollup.tests.config.js
⚠️   No format option was supplied – defaulting to 'es'
https://github.com/rollup/rollup/wiki/JavaScript-API#format
```

P.S2. rollup is not in devDependencies so it make sense to add it

### CODE REVIEW

**Comment by atomiks** [comment]
Thanks, is there a reason not to use `Array.isArray()` to check if it's an array in this case?

**Comment by artyomtrityak** [comment]
I was thinking about it but `Array.isArray` browser support is IE9+. If you are okay about dropping support IE6-8 i can make those change.

**Comment by atomiks** [comment]
Support has been IE10+ since the beginning

**Comment by artyomtrityak** [comment]
cool, will update PR

**Comment by atomiks** [comment]
I've added your changes myself since there is couple problems with the pull, I'll be releasing it in next ver 1.2 soon

**Pull request closed without merging**
