### PR TITLE
 Include scss files in distribution

### PR DESCRIPTION
**Pull request by sqal**
Resolves https://github.com/atomiks/tippyjs/issues/355. I've also added `$tippy-` prefix to all variables so that they do not interfere with other user's variables.

### CODE REVIEW

**Comment by atomiks** [comment]
Can I ask how you'd use these files in an example? Trying to contextualize it a bit

**Comment by sqal** [comment]
@atomiks You would import them this way:

// variable overrides goes before @import

@import "tippyjs/src/scss/tippy";
@import "tippyjs/src/scss/tippy/themes/translucent";

Also, what i forgot to add in this PR is the ability to overwrite theme's variables. I'd like to hear, how would you prefer to have it done? There are ways to do this.

1. Using multiple variables with theme's name:

```scss
$tippy-theme-google-color: #505355 !default;
$tippy-theme-google-color: white !default;
```

2. Or imho, better approach is using maps

```scss
$tippy-theme-google: () !default;
$tippy-theme-google: map-merge(
  (
    color: #505355,
    background-color: white
  ),
  $tippy-theme-google
);
```

Either way, user can easily change any variable's value.

**Comment by KubaJastrz** [comment]
Is it a common practice to include source code in the npm package? This looks fine, but I have mixed feelings about it.

Either way, if we want to implement this, it would be a good idea to include above instructions in the docs somehow.

**Comment by ZhangYiJiang** [comment]
@KubaJastrz It is quite common, especially for frameworks - 

- Bootstrap: https://getbootstrap.com/docs/4.0/getting-started/theming/ 
- Material Components Web - https://github.com/material-components/material-components-web/blob/master/docs/getting-started.md#step-2-include-css-for-a-component 

The benefits of this is that it enables better, smaller builds since as end users we can use our own autoprefixer/PostCSS configs, allowing us to create smaller builds, and makes it easier to theme the styles as mentioned above

**Comment by atomiks** [comment]
I think we need to also do this for animations and themes then.

Also I'd like to figure out a good CSS-in-JS solution for V4 so you don't need to import a CSS file for React

**Comment by atomiks** [comment]
Happy to accept a new PR that does it for themes etc. too!

**Pull request closed without merging**
