### PR TITLE
Use textContent instead of innerHTML to inject CSS

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by atomiks** [comment]
Good catch, didn't think about it in this case. Does it work fine on IE11 etc?

**Comment by marco-c** [comment]
I haven't tested it on IE11 yet, I can try in a bit.

**Comment by atomiks** [comment]
I've tested IE11 using Browserstack + Chrome, FF, Safari, iOS, etc. and it's good.

**Comment by marco-c** [comment]
Thanks for testing it for me ;)

**Comment by atomiks** [comment]
Apologies for the wait: released in `3.0.4`

**Pull request merged**
