### PR TITLE
refObj implementation

### PR DESCRIPTION
**Pull request by atomiks**
@hmtinc
@maxkfranz

Since there were issues with the pull req I implemented the changes into this branch. Can you verify if this is the correct implementation?

### CODE REVIEW

**Comment by hmtinc** [comment]
Looks good. Tried it out with the quick demo from the previous pull request and this implementation seems to work.

**Comment by atomiks** [comment]
One last thing, should the `record` property actually be `attributes`?

And `recordC` in `classList` be `className`?

Also to make it work with `title` as well (not require a HTML template), in the refObject you could make it composable

```javascript
const refObject = {
  attributes: {
    title: 'Tooltip text'
  },
  getBoundingClientRect() {
    return {
      top:  5 + window.pageYOffset,
      left: 5 + window.pageXOffset,
      right: 5 + window.pageXOffset,
      bottom: 220 + window.pageYOffset,
      width: 1,
      height: 1
    }
  },
  get clientWidth() {
    return 30
  },
  get clientHeight() {
    return 30
  },
}

// Should work without needing a html setting
tippy(refObject)
```

then `selector` becomes (inside the main `tippy` function):

```javascript
selector = {
  refObj: true,
  attributes: {
    ...(selector.attributes || {})
  },
  etc
}
```

**Comment by hmtinc** [comment]
Yeah, `record` should probably be attributes and `recordC` should be classNames. 
It was initially only named record because it was keeping a record of values,although in hindsight it probably wasn't the best naming scheme .

**Comment by maxkfranz** [comment]
This looks good to me.  

It's great to be able to support the title, as well.

**Comment by atomiks** [comment]
Great! There's a couple more changes I noticed too:

`recordC` also needed `selector.classList.recordC` not just `selector.recordC` inside those `add/remove/contains` functions since that's where it's located in the object.

`removeAttribute` should use `delete` instead of setting it to `null`.

`contains` inside `classList` should return a strict Boolean

The functions should not use implicit returns if possible (setting not getting?)

Here's the final:

```javascript
  if (isObjectLiteral(selector)) {
    selector = {
      refObj: true,
      attributes: selector.attributes || {},
      getBoundingClientRect: selector.getBoundingClientRect,
      clientWidth: selector.clientWidth,
      clientHeight: selector.clientHeight,
      setAttribute: (key, val) => { selector.attributes[key] = val },
      getAttribute: key => selector.attributes[key],
      removeAttribute: key => { delete selector.attributes[key] },
      addEventListener: () => {},
      removeEventListener: () => {},
      classList: {
        classNames: {},
        add: key => { selector.classList.classNames[key] = true },
        remove: key => {
          selector.classList.classNames[key] = false
          return true
        },
        contains: key => !!selector.classList.classNames[key]
      }
    }
  }
```

Can you verify this works with that demo before I finally commit & merge this? Thank you!

**Comment by hmtinc** [comment]
Tested and it works!

**Pull request merged**
