### PR TITLE
chore: use GitHub actions

### PR DESCRIPTION
**Pull request by atomiks**
Travis is incredibly slow so I want to move to this.

### CODE REVIEW

**Comment by atomiks** [comment]
lol Travis is still going and GitHub Actions finished in two seconds. Bye Travis, you won't be missed 💀

**Comment by KubaJastrz** [comment]
RIP docs deploy

**Comment by atomiks** [comment]
btw this doesn't work 😢 I am trying to fix it and I'll make a new PR. You can add back your docs script in it if you can

**Comment by KubaJastrz** [comment]
I'll be rather busy so probably not today. But you can still do manual deploys if needed.

**Pull request merged**
