### PR TITLE
v2.3 changes

### PR DESCRIPTION
**Pull request by atomiks**
- Add `allowTitleHTML` option (#197)
- Add `tippy.disableAnimations()` static method (#198)
- Use Popper.js for followCursor which alleviates many issues (#188)

@padi @bengarrett

### CODE REVIEW

**Comment by bengarrett** [comment]
Excellent! Unfortunately I am still getting a number of linting errors after building v2.3. In `tippy.all.js`. 

Line 3923
```
          var title = reference.getAttribute('title');
          if (title) {
            content.innerHTML = tippy.title = title;
            removeTitle(reference);
          }
```

Line 234
```
    if (html instanceof Element) {
      content.appendChild(html);
      templateId = '#' + html.id || 'tippy-html-template';
    } else {
      content.innerHTML = document.querySelector(html).innerHTML;
      templateId = html;
    }
```

`tipsy.js` also has from line 223
```
  if (html) {
    var templateId = void 0;

    if (html instanceof Element) {
      content.appendChild(html);
      templateId = '#' + html.id || 'tippy-html-template';
    } else {
      content.innerHTML = document.querySelector(html).innerHTML;
      templateId = html;
    }

    popper.setAttribute('data-html', '');
    interactive && popper.setAttribute('tabindex', '-1');
    tooltip.setAttribute('data-template-id', templateId);
  } else {
    content.innerHTML = title;
  }
```

**Comment by atomiks** [comment]
@bengarrett check latest commit. Hopefully that tricks it

**Comment by bengarrett** [comment]
All working now! Thanks for that!

Curiously the minified versions still trigger a single lint error. It's not important because web extensions do not need to use minified JS but I guess the compressor must refactor the tricked code?

**Comment by mihaisavezi** [comment]
has this been disabled ?

**Pull request merged**
